!#/bin/bash

echo "Hello World"
echo "$(whoami)"
echo "Today is $(date)"
echo "The current directory is $(pwd)"
echo "The current shell is $SHELL"
echo "The current user is $USER"
echo "The current hostname is $(hostname)"
echo "The current time is $(date +%T)"
echo "The current date is $(date +%Y-%m-%d)"
echo "The current year is $(date +%Y)"
echo "The current month is $(date +%m)"
echo "The current day is $(date +%d)"
echo "The current week is $(date +%U)"
echo "The current day of the week is $(date +%A)"
echo "The current day of the year is $(date +%j)"
echo "The current timezone is $(date +%Z)"
echo "The current epoch time is $(date +%s)"
echo "The current date and time is $(date)"
echo "The current date and time in UTC is $(date -u)"
echo "The current date and time in ISO 8601 format is $(date -Iseconds)"
echo "The current date and time in RFC 2822 format is $(date -R)"
echo "The current date and time in RFC 3339 format is $(date -Iseconds)"
echo "The current date and time in RFC 3339 format with timezone is $(date -Iseconds -u)"
echo "The current date and time in RFC 3339 format with timezone and milliseconds is $(date -Iseconds -u --rfc-3339=ns)"